"""SHAP page: beeswarm + bar + per-stock drilldown.

Beeswarm is the canonical paper-style plot (paper p.7); rendered from the PNG
generated by main.py's call to `shap.summary_plot`. Bar chart and drilldown
are derived live from the cached parquet artifacts.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import plotly.express as px
import streamlit as st

from app.lib import data_loader as dl
from src.config import PROJECT_ROOT

st.title("SHAP — feature importance")
st.caption(
    "Top: paper-style beeswarm (one row per feature, dot = one observation, "
    "color = feature value low→high). Paper p.7 finds R1W is #1 and 7-day EPS "
    "revisions (UPDOWN1W) is #2 — note that the latter is absent here (FMP "
    "Starter does not expose historical EPS revisions; UPDOWN1W_RATINGS is "
    "the rating-action proxy)."
)

importance = dl.get("feature_importance")
shap_values = dl.get("shap_values")
beeswarm_png = PROJECT_ROOT / "notebooks" / "figures" / "shap_summary.png"

if importance is None and shap_values is None and not beeswarm_png.exists():
    dl.render_no_data_warning("feature_importance.parquet / shap_values.parquet / shap_summary.png")
    st.stop()

st.subheader("Beeswarm — paper p.7 style")
if beeswarm_png.exists():
    st.image(str(beeswarm_png), use_container_width=True)
    st.caption(
        f"Source: {beeswarm_png.relative_to(PROJECT_ROOT)} — generated by "
        "`shap.summary_plot` over the last `diagnostics.shap_test_weeks` of "
        "test predictions."
    )
else:
    st.info("`shap_summary.png` not found. Run `python -m src.main` to produce it.")

st.subheader("Mean |SHAP| ranking")
if importance is not None:
    series = importance.iloc[:, 0].sort_values()
    fig = px.bar(
        series,
        orientation="h",
        labels={"value": "Mean |SHAP|", "index": "Feature"},
    )
    fig.update_layout(showlegend=False, margin=dict(l=40, r=20, t=20, b=40))
    st.plotly_chart(fig, use_container_width=True)

if shap_values is not None:
    st.subheader("Per-stock SHAP attributions")
    if isinstance(shap_values.index, pd.MultiIndex) and "ticker" in shap_values.index.names:
        col1, col2 = st.columns([1, 1])
        with col1:
            tickers = sorted(shap_values.index.get_level_values("ticker").unique())
            sel_t = st.selectbox("Ticker", tickers)
        with col2:
            dates = sorted(
                shap_values.xs(sel_t, level="ticker").index.unique(), reverse=True
            )
            sel_d = st.selectbox(
                "Date", dates, format_func=lambda d: pd.Timestamp(d).date().isoformat()
            )
        row = shap_values.loc[(sel_d, sel_t)]
        st.dataframe(row.to_frame("SHAP value").sort_values("SHAP value"), use_container_width=True)
